//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigo
    {
        public string Code { get; set; }
        public string Tipo { get; set; }
        public string Grupo { get; set; }
        public string Descricao { get; set; }
        public string NumberCode { get; set; }
        public int Stock { get; set; }
    }
}
