//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public string CustomerID { get; set; }
        public string AccountID { get; set; }
        public string CustomerTaxID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BillingAddressID { get; set; }
        public string Telephone { get; set; }
        public int SelfBillingIndicator { get; set; }
        public string CustomerName { get; set; }
        public string Currency { get; set; }
        public string CustomerEmail { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
    
        public virtual BillingAddress BillingAddress { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
