//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstREST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountPayable> AccountPayable { get; set; }
        public virtual DbSet<AccountReceivable> AccountReceivable { get; set; }
        public virtual DbSet<BillingAddress> BillingAddress { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DocCompra> DocCompra { get; set; }
        public virtual DbSet<DocumentTotals> DocumentTotals { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<LinhaDocCompra> LinhaDocCompra { get; set; }
        public virtual DbSet<OrderReferences> OrderReferences { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<SalesInvoices> SalesInvoices { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Tax> Tax { get; set; }
    }
}
