//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstREST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountPayable> AccountPayable { get; set; }
        public virtual DbSet<AccountReceivable> AccountReceivable { get; set; }
        public virtual DbSet<AllSalesInvoicesInfo> AllSalesInvoicesInfo { get; set; }
        public virtual DbSet<BillingAddress> BillingAddress { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DocCompra> DocCompra { get; set; }
        public virtual DbSet<LinhaDocCompra> LinhaDocCompra { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<SaleInvoice> SaleInvoice { get; set; }
        public virtual DbSet<SaleInvoiceLine> SaleInvoiceLine { get; set; }
        public virtual DbSet<SaleInvoiceTotal> SaleInvoiceTotal { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Teste> Teste { get; set; }
    }
}
